env:
  browser: true
ignorePatterns: ['**/__test__/**', '**/dist/**', '**/vite.config.ts', '**/vite-env-override.d.ts']
#files: ['**/src/**/*.ts', '**/src/**/**.tsx']
globals:
  performance: readonly

#required for jsx
settings:
  react:
    version: detect

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - "plugin:import/typescript"
  - 'plugin:react/jsx-runtime'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json

plugins: ["react", "@typescript-eslint",  "react-hooks", "react-refresh"]
rules:
  react-hooks/rules-of-hooks:   error
  react-hooks/exhaustive-deps:  warn
  react-refresh/only-export-components: [
    'warn',
    {allowConstantExport: true},
  ]
  '@typescript-eslint/ban-ts-comment':              off
  '@typescript-eslint/ban-types': [ "error",
    {
      "types": {
#        "String": false,
#        "Boolean": false,
#        "Number": false,
#        "Symbol": false,
#        "{}": false,
#        "Object": false,
#        "object": false,
        "Function": false,
      },
      "extendDefaults": true
    }
  ]
  '@typescript-eslint/prefer-literal-enum-member':  error
  '@typescript-eslint/no-explicit-any':             off
  '@typescript-eslint/no-non-null-assertion':       off
  '@typescript-eslint/no-unused-vars': [
    'off',
    {
      argsIgnorePattern:         ^_,
      varsIgnorePattern:         ^_,
      caughtErrorsIgnorePattern: ^_
    }
  ]


