private: true
engines:
  node: '>=18.17.1'
  pnpm: '>=8.7.4'

pnpm:
  overrides:
    marked@<4.10.10: '>=4.0.10'  # this is a placeholder unnecessary example of a pnpm package override
dependencies:
  typescript: ^4.9.5  # placeholder dependency, could be by application upgrade this when react 19 available?
devDependencies:
  "@testing-library/jest-dom": ^5.17.0
  "@testing-library/react": ^13.4.0
  "@testing-library/user-event": ^13.5.0
  "@types/jest": ^27.5.2
  "@types/node": ^18.17.1
  "@types/react": ^18.2.61
  "@types/react-dom": ^18.2.19
  "@types/react-redux": ~7.1.25
workspaces:
  packages:
    - apps/roots
    - apps/ticket
    - apps/zclient
    - libs/boot
    - libs/fizbin
    - libs/th-utils

