name: ticket
version: 0.1.0
private: true
dependencies:
  react:                        ^18.2.0
  react-dom:                    ^18.2.0
#  react-vis-graph-wrapper:      ~0.1.3
  redux:                        ~4.2.1
  react-redux:                  ~7.2.9
  reselect:                     ~4.1.7
  typescript:                   ^4.9.5
  vis-network:                  '~9.1.9'
  web-vitals:                   ^2.1.4

devDependencies:
  "@testing-library/jest-dom":    ^5.17.0
  "@testing-library/react":       ^13.4.0
  "@testing-library/user-event":  ^13.5.0
  "@types/jest":                  ^27.5.2
  "@types/node":                  ^16.18.86
  "@types/react":                 ^18.2.61
  "@types/react-dom":             ^18.2.19
  "@vitejs/plugin-react-swc":     ~3.3.2
  vite:                           ~4.5.2
  vite-bundle-visualizer:         ~0.8.1

scripts:
  start:   vite
  build:   tsc && vite build
  preview: vite preview

eslintConfig:
  extends:
    - react-app
    - react-app/jest

browserslist:
  production: [">0.2%","not dead", "not op_mini all"]
  "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]


