name: ticket
version: 0.1.0
private: true

dependencies:
  immer:                          ~10.0.4
  react:                          ^18.2.0
  react-dom:                      ^18.2.0
  redux:                          ~4.2.1
  react-redux:                    ~7.2.9
  reselect:                       ~4.1.7
  typescript:                     ^4.9.5
  vis-network:                    ~9.1.9
  web-vitals:                     ^2.1.4

devDependencies:
  "@testing-library/jest-dom":    ^5.17.0
  "@testing-library/react":       ^13.4.0
  "@testing-library/user-event":  ^13.5.0
  "@types/jest":                  ^27.5.2
  "@types/node":                  ^18.17.1
  "@types/react":                 ^18.2.61
  "@types/react-dom":             ^18.2.19
  "@types/react-redux":           ~7.1.25
  "@vitejs/plugin-react-swc":     ~3.6.0
  redux-devtools-extension:       ~2.13.9
  vite:                           ~5.2.6
  vite-bundle-visualizer:         ~1.1.0

scripts:
  start:   VITE_CJS_IGNORE_WARNING=true vite  #it looks like react-swc plugin might be cause of the warning I am turning off?
  build:   tsc && vite build
  preview: vite preview

eslintConfig:
  extends:
    - react-app
    - react-app/jest

browserslist:
  production: [">0.2%","not dead", "not op_mini all"]
  "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]


