
private: true
scripts:
  index:       node ./scripts/library-index-generator.js ${1:---watch=false}
  indexOnce:   node ./scripts/library-index-generator.js
  indexWatch:  node ./scripts/library-index-generator.js --watch
  lint:        eslint . --ext js,jsx,ts,tsx
  mgStart:     docker compose -f scripts/docker-compose-memgraph.yaml up
  mgStop:      docker compose -f scripts/docker-compose-memgraph.yaml down
engines:
  node:        ">=18.17.1"
  pnpm:        ">=8.7.4"

pnpm:
  overrides:
    "marked@<4.10.10":                ">=4.0.10"

devDependencies:
  "@hzamir/npm-run-all":              ~4.1.7
  "@types/node":                      ~20.12.10
  "@types/react":                     ~18.2.64
  "@types/react-dom":                 ~18.2.21
  "@types/react-redux":               ~7.1.25
  "@types/styled-components":         ~5.1.26

  "@types/stylis":                    ~4.2.5     # unsure if even stylis is needed, is there benefit to stylis types also
  "@vitejs/plugin-react-swc":         ~3.6.0
  "@typescript-eslint/eslint-plugin": ~7.7.0
  "@typescript-eslint/parser":        ~7.7.0
  eslint:                             ~8.57.0
  eslint-plugin-import:               ~2.29.1
  eslint-plugin-react-hooks:          ~4.6.0
  eslint-plugin-react-refresh:        ~0.4.6
  eslint-plugin-react:                ~7.34.1
  redux-devtools-extension:           ~2.13.9
  chokidar:                           ~3.6.0     # for file-watching in build utilities
  glob:                               ~10.3.12
  lerna:                              ~8.1.2     # if we use lerna, it will probably fail on top level package.yaml so will need script to generate package.json
  minimist:                           ~1.2.8     # lightweight lib for argument processing in nodejs scripts
  ts-node:                            ~10.9.1    # simplifies using typescript for build scripts
  typescript:                         ~5.4.5
  vite:                               ~5.2.8     # standardizing on vite for building libs and apps
  vitest:                             ~1.4.0     # a jest-like test runner for vite
  vite-bundle-visualizer:             ~1.1.0

  # these are for electron app projects, e.g. lectro
  electron:                           ~30.0.1
  electron-builder:                   ~24.13.3
  vite-plugin-electron:               ~0.28.7
  vite-plugin-electron-renderer:      ~0.14.5


