packages:
  - "apps/**"      # applications
  - "servers/**"   # servers
  - "cmps/**"      # components
  - "libs/**"      # libraries (aside from components)
  - "scripts"      # scripts (keeps IDE happy, allows typescript scripts that use internal libs)
  - '!**/test/**'  # exclude packages that are inside test directories
