
name: roots
private: true
version: 0.0.0
type: module
author: Haim Zamir
license: MIT
scripts:
  start:   VITE_CJS_IGNORE_WARNING=true vite  #it looks like react-swc plugin might be cause of the warning I am turning off?
  dev: vite
  build: tsc && vite build
  preview: vite preview
  lint:    eslint . --ext js,jsx,ts,tsx

dependencies:
  "@therious/actions":     "workspace:*"
  "@therious/boot":        "workspace:*"
  "@therious/utils":       "workspace:*"
  react:                   ~18.2.0
  react-dom:               ~18.2.0
  react-json-tree:         ~0.18.0
  styled-components:       ~5.3.6
  ag-grid-community:       ~32.0.2
  ag-grid-react:           ~32.0.2
  axios:                   ~1.6.8
  browser-fs-access:       ~0.33.0
  js-yaml:                 ~4.1.0
  notistack:               ^3.0.0-alpha.11
  react-contexify:         6.0.0
  react-redux:             ~7.2.9
  react-router-dom:        ~6.8.1
  redux:                   ~4.2.1
  reflect-metadata:        ~0.1.13
  reselect:                ~4.1.7
  tsyringe:                ~4.8.0
  react-vis-graph-wrapper: ~0.1.3
  vis-network:             ~9.1.9

browserslist:   # vite ignores this ,uses fine grained js targets (esnext, es2021, etc) but its postCss does exploit it
  production:  &prod ["Chrome >= 112", "Edge >= 112", "Firefox >= 112", "Safari >= 16.4"]
  development: *prod # use same targets for dev and prod
