name:                             '@therious/graphic'
version:                          0.2.0
private:                          true
author:                           Haim Zamir <hzamir@gmail.com>
license:                          MIT
type: module
dependencies:
  '@therious/ddd':                &ws 'workspace:*'
  '@therious/utils':              *ws
  '@therious/boot':               *ws
  '@therious/fsm':                *ws
  '@therious/actions':            *ws
  '@therious/components':         *ws
  immer:                          ~10.0.4
  js-yaml:                        ~4.1.0
  react:                          ^18.2.0
  react-dom:                      ^18.2.0
  react-hook-signal:              ^0.0.1-rc # react hooks for signal polyfill
  signal-polyfill:                ~0.1.0   # TC39 proposal for Signals official polyfill
  '@tanstack/react-query':        ~5.28.9  # trying out react-query, for now
  redux:                          ~4.2.1
  react-redux:                    ~7.2.9
  reselect:                       ~4.1.7
  reflect-metadata:               ~0.1.13 # needed for tsyringe, and fancy decorator stuff
  styled-components:              ~6.1.8
  stylis:                         ~4.3.1  # a dependency of styled-components, apparently is it necessary to pull directly
  typescript:                     ~5.4.5  # upgrade this when react 19 available?
  vis-network:                    ~9.1.9  # used to plot railroad track network
  '@viz-js/viz':                  ~3.4.0  # (feb 2024)   viz-js wasm renderer for dot language
  '@sequencemedia/graphviz-react':  ~0.0.81  # (feb 2024)   d3 based graphviz
  d3-graphviz:                    ~5.4.0  # (apr 2024) d3 based graphviz, also uses a (different) wasm renderer than viz-js, can animate changes to graph
  xstate:                         4.28.1  # or maybe 4.28.1 or 4.23.1 is last one latest= 5.9.1 I have actually successfully used?
devDependencies:
  '@types/d3-graphviz':          ~2.6.10  #if it sticks, move this to top package.yaml with other dev dependencies?

scripts:
  start:   VITE_CJS_IGNORE_WARNING=true vite  #it looks like react-swc plugin might be cause of the warning I am turning off?
  dev:     VITE_CJS_IGNORE_WARNING=true vite
  build:   tsc && vite build
  preview: vite preview
  lint:    eslint . --ext js,jsx,ts,tsx


browserslist:   # vite ignores this ,uses fine grained js targets (esnext, es2021, etc) but its postCss does exploit it
  production:  &prod ["Chrome >= 112", "Edge >= 112", "Firefox >= 112", "Safari >= 16.4"]
  development: *prod # use same targets for dev and prod


