defmodule ElectionsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :elections

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_elections_key",
    signing_salt: "FQAWRKeI",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", ElectionsWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :elections,
    gzip: not code_reloading?,
    only_matching: ElectionsWeb.static_path_patterns(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  
  # Conditional request logging - only log when debug_logging is enabled
  # When debug_logging is false, exclude POST /api/votes to avoid performance impact
  @debug_logging Application.compile_env(:elections, :debug_logging, false)
  if @debug_logging do
    plug Plug.Logger
  else
    # Filter out POST /api/votes requests to improve performance at high vote rates
    plug Plug.Logger, log: :info, exclude: ["/api/votes"]
  end

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ElectionsWeb.Router
end
