import React, { useState } from 'react';

// Import build info generated at build time
// This file is generated by scripts/generate-build-info.js during build
import buildInfoJson from '../build-info.json';

interface BuildInfoData {
  commitHash: string;
  branch: string;
  authorDate: string;
  commitDate: string;
  buildDate: string;
  mnemonic?: string;
}

interface ServerBuildInfo {
  commitHash: string;
  branch: string;
  authorDate: string;
  commitDate: string;
  buildDate: string;
}

interface BuildInfoProps {
  serverBuildInfo?: ServerBuildInfo | null;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * BuildInfo component displays build information (commit hash, branch, dates)
 * 
 * This component is designed to be reusable across all applications.
 * For applications without servers, only the UI build info will be displayed.
 * 
 * Styled to match UserProfile widget: same height, padding, background, border-radius, border
 * Positioned on the right side, just before UserProfile widget with small gap
 * 
 * @param serverBuildInfo - Optional full server build info (not just hash)
 * @param className - Optional CSS class name
 * @param style - Optional inline styles
 */
export function BuildInfo({ serverBuildInfo, className, style }: BuildInfoProps) {
  const uiBuildInfo: BuildInfoData = buildInfoJson as BuildInfoData;
  const [showTooltip, setShowTooltip] = useState(false);
  const [tooltipPosition, setTooltipPosition] = useState<'top' | 'bottom'>('top');
  const containerRef = React.useRef<HTMLDivElement>(null);
  const tooltipRef = React.useRef<HTMLDivElement>(null);
  
  const hashesMatch = serverBuildInfo?.commitHash === uiBuildInfo.commitHash;
  const showRed = serverBuildInfo && !hashesMatch;
  
  // Calculate tooltip position to avoid clipping
  React.useEffect(() => {
    if (showTooltip && containerRef.current && tooltipRef.current) {
      const containerRect = containerRef.current.getBoundingClientRect();
      const tooltipRect = tooltipRef.current.getBoundingClientRect();
      const viewportHeight = window.innerHeight;
      const spaceAbove = containerRect.top;
      const spaceBelow = viewportHeight - containerRect.bottom;
      const tooltipHeight = tooltipRect.height || 200; // Estimate if not yet rendered
      
      // Position above if there's enough space, otherwise below
      if (spaceAbove >= tooltipHeight + 10) {
        setTooltipPosition('top');
      } else if (spaceBelow >= tooltipHeight + 10) {
        setTooltipPosition('bottom');
      } else {
        // Not enough space on either side - choose the side with more space
        setTooltipPosition(spaceAbove > spaceBelow ? 'top' : 'bottom');
      }
    }
  }, [showTooltip]);
  
  // Build tooltip content - grey out server info that matches UI
  const tooltipContent = (
    <div style={{ padding: '0.5rem', fontSize: '10px', fontFamily: 'monospace', lineHeight: '1.4' }}>
      <div style={{ fontWeight: 'bold', marginBottom: '0.25rem' }}>UI Build Info:</div>
      <div>Hash: {uiBuildInfo.commitHash}</div>
      <div>Branch: {uiBuildInfo.branch}</div>
      <div>Author: {uiBuildInfo.authorDate}</div>
      <div>Commit: {uiBuildInfo.commitDate}</div>
      <div>Build: {uiBuildInfo.buildDate}</div>
      {uiBuildInfo.mnemonic && <div>Mnemonic: "{uiBuildInfo.mnemonic.replace(/-/g, ' ')}"</div>}
      
      {serverBuildInfo && (
        <>
          <div style={{ marginTop: '0.5rem', fontWeight: 'bold' }}>Server Build Info:</div>
          <div style={{ color: serverBuildInfo.commitHash === uiBuildInfo.commitHash ? '#999' : '#fff' }}>
            Hash: {serverBuildInfo.commitHash}
          </div>
          <div style={{ color: serverBuildInfo.branch === uiBuildInfo.branch ? '#999' : '#fff' }}>
            Branch: {serverBuildInfo.branch}
          </div>
          <div style={{ color: serverBuildInfo.authorDate === uiBuildInfo.authorDate ? '#999' : '#fff' }}>
            Author: {serverBuildInfo.authorDate}
          </div>
          <div style={{ color: serverBuildInfo.commitDate === uiBuildInfo.commitDate ? '#999' : '#fff' }}>
            Commit: {serverBuildInfo.commitDate}
          </div>
          <div style={{ color: serverBuildInfo.buildDate === uiBuildInfo.buildDate ? '#999' : '#fff' }}>
            Build: {serverBuildInfo.buildDate}
          </div>
          
          {!hashesMatch && (
            <div style={{ marginTop: '0.5rem', fontWeight: 'bold', color: '#d32f2f' }}>
              Hashes don't match!
            </div>
          )}
        </>
      )}
    </div>
  );
  
  // Match UserProfile styling exactly: same padding, background, border-radius, border
  // Same height by using same padding and single line display
  const defaultStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: '0.5rem 1rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    border: '1px solid #dee2e6',
    fontSize: '10px',
    color: showRed ? '#d32f2f' : '#666',
    fontFamily: 'monospace',
    lineHeight: '1.2',
    position: 'relative',
    cursor: 'help',
    ...style
  };
  
  const tooltipStyle: React.CSSProperties = {
    position: 'absolute',
    left: '50%',
    transform: 'translateX(-50%)',
    ...(tooltipPosition === 'top' 
      ? { bottom: '100%', marginBottom: '0.5rem' }
      : { top: '100%', marginTop: '0.5rem' }
    ),
    background: '#333',
    color: '#fff',
    padding: '0.5rem',
    borderRadius: '4px',
    zIndex: 10000,
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
    pointerEvents: 'none',
    minWidth: '300px',
    maxWidth: '400px',
    whiteSpace: 'normal' as const,
    maxHeight: '80vh',
    overflowY: 'auto' as const
  };
  
  return (
    <div 
      ref={containerRef}
      className={className} 
      style={defaultStyle}
      onMouseEnter={() => setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
      title="Hover for full build info"
    >
      <div>UI: {uiBuildInfo.commitHash}</div>
      {uiBuildInfo.mnemonic && (
        <div>"{uiBuildInfo.mnemonic.replace(/-/g, ' ')}"</div>
      )}
      
      {showTooltip && (
        <div ref={tooltipRef} style={tooltipStyle}>
          {tooltipContent}
        </div>
      )}
    </div>
  );
}
