import React, { useState } from 'react';

// Import build info generated at build time
// This file is generated by scripts/generate-build-info.js during build
import buildInfoJson from '../build-info.json';

interface BuildInfoData {
  commitHash: string;
  branch: string;
  authorDate: string;
  commitDate: string;
  buildDate: string;
  mnemonic?: string;
}

interface ServerBuildInfo {
  commitHash: string;
  branch: string;
  authorDate: string;
  commitDate: string;
  buildDate: string;
}

interface BuildInfoProps {
  serverBuildInfo?: ServerBuildInfo | null;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * BuildInfo component displays build information (commit hash, branch, dates)
 * 
 * This component is designed to be reusable across all applications.
 * For applications without servers, only the UI build info will be displayed.
 * 
 * Styled to match UserProfile widget: same padding, background, border-radius, border
 * Positioned on the right side, to the left of UserProfile widget
 * 
 * @param serverBuildInfo - Optional full server build info (not just hash)
 * @param className - Optional CSS class name
 * @param style - Optional inline styles
 */
export function BuildInfo({ serverBuildInfo, className, style }: BuildInfoProps) {
  const uiBuildInfo: BuildInfoData = buildInfoJson as BuildInfoData;
  const [showTooltip, setShowTooltip] = useState(false);
  
  const hashesMatch = serverBuildInfo?.commitHash === uiBuildInfo.commitHash;
  
  // Calculate time differences if hashes don't match
  let buildTimeDiff: string | null = null;
  let authorTimeDiff: string | null = null;
  
  if (serverBuildInfo && !hashesMatch) {
    try {
      const uiBuildTime = new Date(uiBuildInfo.buildDate).getTime();
      const serverBuildTime = new Date(serverBuildInfo.buildDate).getTime();
      const buildDiffMs = Math.abs(uiBuildTime - serverBuildTime);
      const buildDiffSec = Math.floor(buildDiffMs / 1000);
      const buildDiffMin = Math.floor(buildDiffSec / 60);
      
      if (buildDiffMin > 0) {
        buildTimeDiff = `${buildDiffMin} minute${buildDiffMin !== 1 ? 's' : ''}`;
      } else {
        buildTimeDiff = `${buildDiffSec} second${buildDiffSec !== 1 ? 's' : ''}`;
      }
      
      const uiAuthorTime = new Date(uiBuildInfo.authorDate).getTime();
      const serverAuthorTime = new Date(serverBuildInfo.authorDate).getTime();
      const authorDiffMs = Math.abs(uiAuthorTime - serverAuthorTime);
      const authorDiffSec = Math.floor(authorDiffMs / 1000);
      const authorDiffMin = Math.floor(authorDiffSec / 60);
      const authorDiffHour = Math.floor(authorDiffMin / 60);
      
      if (authorDiffHour > 0) {
        authorTimeDiff = `${authorDiffHour} hour${authorDiffHour !== 1 ? 's' : ''}`;
      } else if (authorDiffMin > 0) {
        authorTimeDiff = `${authorDiffMin} minute${authorDiffMin !== 1 ? 's' : ''}`;
      } else {
        authorTimeDiff = `${authorDiffSec} second${authorDiffSec !== 1 ? 's' : ''}`;
      }
    } catch (e) {
      // Ignore date parsing errors
    }
  }
  
  // Build tooltip content
  const tooltipContent = (
    <div style={{ padding: '0.5rem', fontSize: '10px', fontFamily: 'monospace', lineHeight: '1.4' }}>
      <div style={{ fontWeight: 'bold', marginBottom: '0.25rem' }}>UI Build Info:</div>
      <div>Hash: {uiBuildInfo.commitHash}</div>
      <div>Branch: {uiBuildInfo.branch}</div>
      <div>Author: {uiBuildInfo.authorDate}</div>
      <div>Commit: {uiBuildInfo.commitDate}</div>
      <div>Build: {uiBuildInfo.buildDate}</div>
      {uiBuildInfo.mnemonic && <div>Mnemonic: {uiBuildInfo.mnemonic}</div>}
      
      {serverBuildInfo && (
        <>
          <div style={{ marginTop: '0.5rem', fontWeight: 'bold' }}>Server Build Info:</div>
          <div>Hash: {serverBuildInfo.commitHash}</div>
          <div>Branch: {serverBuildInfo.branch}</div>
          <div>Author: {serverBuildInfo.authorDate}</div>
          <div>Commit: {serverBuildInfo.commitDate}</div>
          <div>Build: {serverBuildInfo.buildDate}</div>
          
          {!hashesMatch && (
            <>
              <div style={{ marginTop: '0.5rem', fontWeight: 'bold', color: '#d32f2f' }}>Differences:</div>
              {buildTimeDiff && <div>Build time diff: {buildTimeDiff}</div>}
              {authorTimeDiff && <div>Author time diff: {authorTimeDiff}</div>}
            </>
          )}
        </>
      )}
    </div>
  );
  
  // Match UserProfile styling: padding: 0.5rem 1rem, background: #f8f9fa, border-radius: 8px, border: 1px solid #dee2e6
  // Position on right side, to the left of UserProfile with gap
  const defaultStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '0.25rem',
    padding: '0.5rem 1rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    border: '1px solid #dee2e6',
    fontSize: '10px',
    color: '#666',
    fontFamily: 'monospace',
    lineHeight: '1.2',
    marginRight: '0.75rem', // Gap to the left of UserProfile
    marginLeft: 'auto', // Push to right side
    position: 'relative',
    cursor: 'help',
    ...style
  };
  
  const tooltipStyle: React.CSSProperties = {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    marginBottom: '0.5rem',
    background: '#333',
    color: '#fff',
    padding: '0.5rem',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
    zIndex: 10000,
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
    pointerEvents: 'none',
    minWidth: '300px',
    whiteSpace: 'normal' as const
  };
  
  return (
    <div 
      className={className} 
      style={defaultStyle}
      onMouseEnter={() => setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
      title="Hover for full build info"
    >
      {hashesMatch ? (
        // Hashes match - only show UI info (don't duplicate)
        <>
          <div>UI: {uiBuildInfo.commitHash}</div>
          {uiBuildInfo.mnemonic && (
            <div>{uiBuildInfo.mnemonic}</div>
          )}
        </>
      ) : (
        // Hashes don't match - show both
        <>
          {serverBuildInfo && (
            <div>Server: {serverBuildInfo.commitHash}</div>
          )}
          <div>UI: {uiBuildInfo.commitHash}</div>
          {uiBuildInfo.mnemonic && (
            <div>{uiBuildInfo.mnemonic}</div>
          )}
          {buildTimeDiff && authorTimeDiff && (
            <div style={{ fontSize: '9px', color: '#d32f2f' }}>
              Diff: {buildTimeDiff} build, {authorTimeDiff} author
            </div>
          )}
        </>
      )}
      
      {showTooltip && (
        <div style={tooltipStyle}>
          {tooltipContent}
        </div>
      )}
    </div>
  );
}
