import React from 'react';

// Import build info generated at build time
// This file is generated by scripts/generate-build-info.js during build
import buildInfoJson from '../build-info.json';

interface BuildInfoData {
  commitHash: string;
  branch: string;
  authorDate: string;
  commitDate: string;
  buildDate: string;
}

interface BuildInfoProps {
  serverCommitHash?: string | null;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * BuildInfo component displays build information (commit hash, branch, dates)
 * 
 * This component is designed to be reusable across all applications.
 * For applications without servers, only the UI build info will be displayed.
 * 
 * @param serverCommitHash - Optional server commit hash to display alongside UI hash
 * @param className - Optional CSS class name
 * @param style - Optional inline styles
 */
export function BuildInfo({ serverCommitHash, className, style }: BuildInfoProps) {
  const uiBuildInfo: BuildInfoData = buildInfoJson as BuildInfoData;
  
  const defaultStyle: React.CSSProperties = {
    position: 'fixed',
    top: '0.5rem',
    left: '0.5rem',
    fontSize: '10px',
    color: '#666',
    fontFamily: 'monospace',
    zIndex: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    padding: '0.25rem 0.5rem',
    borderRadius: '4px',
    ...style
  };
  
  return (
    <div className={className} style={defaultStyle}>
      {serverCommitHash && (
        <div>Server: {serverCommitHash}</div>
      )}
      <div>UI: {uiBuildInfo.commitHash}</div>
    </div>
  );
}
