name:                             scraper
version:                          0.1.0
private:                          true
type:                             module
dependencies:
  js-yaml:                        ~4.1.1
  puppeteer:                      ~21.6.0
  '@therious/boot':               'workspace:*'
  reflect-metadata:               ~0.1.13
  tsyringe:                       ~4.8.0
devDependencies:
  typescript:                     ~5.4.5
  tsx:                            ~4.7.0
  '@types/js-yaml':               ~4.0.9
  '@types/node':                  ~20.11.0
scripts:
  start:    tsx scraper.ts

