name: admin
version: 0.1.0
private: true
dependencies:
  '@therious/actions': workspace:*
  '@therious/users':   workspace:*
  '@therious/components': workspace:*
  ag-grid-community: ~32.0.2
  ag-grid-react: ~32.0.2
  firebase: ~10.12.0
  notistack: ~3.0.1
  react: ~18.2.0
  react-contexify: 6.0.0
  react-dom: ~18.2.0
  react-redux: ~7.2.9
  react-router-dom: ~6.24.0
  redux: ~4.2.1
  styled-components: ~6.1.8
  typescript: ~5.4.5
scripts:
  start: vite
  dev: vite
  build: tsc && vite build
  preview: vite preview --port 5175
browserslist:
  production:
    - Chrome >= 112
  development:
    - Chrome >= 112
