name:                         '@therious/zclient'
version:                      0.5.0
private:                      true
author:                       Haim Zamir <hzamir@gmail.com>
license:                      MIT

dependencies:
  "@therious/actions":        &ws 'workspace:*'
  "@therious/boot":           *ws
  "@therious/components":     *ws
  "@therious/fsm":            *ws
  "@therious/utils":          *ws
  ag-grid-community:          &ag ~30.2.0
  ag-grid-enterprise:         *ag
  ag-grid-react:              *ag
  axios:                      ~1.6.8
  luxon:                      ~1.28.1
  ramda:                      ~0.27.1
  react:                      ~18.2.0
  react-contexify:            6.0.0
  react-dom:                  ~18.2.0
  react-redux:                ~7.2.9
  redux:                      ~4.2.1
  reflect-metadata:           ~0.1.13
  reselect:                   ~4.1.7
  styled-components:          ~6.1.8
  xstate:                     4.28.1

scripts:
  start:       VITE_CJS_IGNORE_WARNING=true vite  #it looks like react-swc plugin might be cause of the warning I am turning off?
  build:       tsc && vite build
  preview:     vite preview
  lint:        eslint . --ext js,jsx,ts,tsx

browserslist:   # vite ignores this ,uses fine grained js targets (esnext, es2021, etc) but its postCss does exploit it
  production:  &prod ["Chrome >= 112", "Edge >= 112", "Firefox >= 112", "Safari >= 16.4"]
  development: *prod # use same targets for dev and prod


