import React from 'react';
import { BuildInfo } from '@therious/components';

// Import build info generated at build time
// This file is generated by scripts/generate-build-info.js during build
let buildInfoJson: any = null;
try {
  // @ts-ignore - build-info.json is generated at build time
  buildInfoJson = require('./build-info.json');
} catch (e) {
  // File doesn't exist - dev mode or not built yet
  // Component will gracefully degrade
}

/**
 * Wrapper component that loads build-info.json and passes it to BuildInfo
 * This makes it trivial to add BuildInfo to any app - just import and render this component
 */
export function BuildInfoWrapper(props: { className?: string; style?: React.CSSProperties }) {
  return <BuildInfo buildInfo={buildInfoJson} {...props} />;
}

