name: elect
version: 0.1.0
private: true
dependencies:
  '@atlaskit/pragmatic-drag-and-drop': ~1.3.0
  '@therious/actions': workspace:*
  '@therious/boot': workspace:*
  '@therious/utils': workspace:*
  immer: ~10.0.4
  muuri: ^0.9.5
  muuri-react: ^3.1.7
  phoenix: ~1.7.21
  react: ~18.2.0
  react-dom: ~18.2.0
  react-redux: ~7.2.9
  react-router-dom: ~6.24.0
  redux: ~4.2.1
  reflect-metadata: ~0.1.13
  reselect: ~4.1.7
  styled-components: ~6.1.8
  typescript: ~5.4.5
scripts:
  start: pnpm --filter . indexOnce && VITE_CJS_IGNORE_WARNING=true vite
  dev: pnpm --filter . indexOnce && VITE_CJS_IGNORE_WARNING=true vite
  build: tsc && vite build
  preview: vite preview --port 5173
  lint: eslint . --ext js,jsx,ts,tsx
  serve: bash scripts/build-and-serve.sh
browserslist:
  production:
    - Chrome >= 112
    - Edge >= 112
    - Firefox >= 112
    - Safari >= 16.4
  development:
    - Chrome >= 112
    - Edge >= 112
    - Firefox >= 112
    - Safari >= 16.4
