# fly.toml app configuration file generated for edgy-api-soup on 2024-06-03T23:37:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'edgy-api-soup'
primary_region = 'ewr'

[env]
AAA_HZ_WAS_HERE = 'howdy'
AAA_HZ_WAS_THERE = 'doody'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
