name:         '@therious/build-scripts'
private:      true
type:         module
scripts:
devDependencies:
  "@hzamir/npm-run-all":              ~4.1.7
  "@types/node":                      ~20.12.10
  "@types/js-yaml":                   ~4.0.9
  js-yaml:                            ~4.1.0
  ts-node:                            ~10.9.1
  typescript:                         ~5.4.5




