name: '@therious/circle'
version: 0.0.1
description: Circle - skeletal vite react app
type: module
scripts:
  start: vite
  build: tsc && vite build
  preview: vite preview

dependencies:
  react: ~18.2.0
  react-dom: ~18.2.0

devDependencies:
  '@types/react': ~18.2.0
  '@types/react-dom': ~18.2.0
  '@vitejs/plugin-react-swc': ~3.7.0
  typescript: ~5.4.5
  vite: ~5.3.1

