name:    ticket
version: 0.1.0
private: true

dependencies:
  '@therious/utils':                  &ws      'workspace:*'
  '@therious/random':                 *ws      # todo get rid of random in favor of utils?
  '@therious/ag-grid':                *ws      # shareable ag-grid utilities
  '@therious/boot':                   *ws
  '@therious/fsm':                    *ws
  '@therious/actions':                *ws      # common set of reduxy-type actions (pure functions, not redux)
  '@therious/components':             *ws
  '@supabase/supabase-js':            ~2.44.3  # running a query directly from client
  '@supabase/realtime-js':            ~2.10.4  # receive db update messages, communicate with other clients
  '@hcaptcha/react-hcaptcha':         ~1.0.0   # a captcha supported by supabase auth
  ag-grid-community:                  ~32.0.2  # look to upgrade, first to 30.2.1 (used in lab), then  32.0.2 (latest)
  ag-grid-react:                      ~32.0.2  # used by mygrid
  axios:                              ~1.13.2   # used by api-middleware till it gets converted to fetch
  date-fns:                           ~3.6.0   # used by date rendering functions for grid
  immer:                              ~10.0.4
  js-yaml:                            ~4.1.1
  notistack:                          ~3.0.1   # NotifyWrapper.tsx uses this
  react:                              ~18.2.0
  react-contexify:                    6.0.0    # context menu, used by MyGrid implementation (on top of ag-grid-react)
  react-dom:                          ~18.2.0
  react-router-dom:                   ~6.24.0
  redux:                              ~4.2.1
  react-redux:                        ~7.2.9
  reselect:                           ~4.1.7
  reflect-metadata:                   ~0.1.13  # needed for tsyringe, and fancy decorator stuff
  styled-components:                  ~6.1.8
  stylis:                             ~4.3.1   # a dependency of styled-components, apparently is it necessary to pull directly
  typescript:                         ~5.4.5   # upgrade this when react 19 available?  todo why isn't this a dev dependency?
  vis-network:                        ~9.1.9   # used to plot railroad track network
  web-vitals:                         ^2.1.4
  xstate:                             4.28.1   # or maybe 4.28.1 or 4.23.1 is last one latest= 5.9.1 I have actually successfully used?

scripts:
  start:   VITE_CJS_IGNORE_WARNING=true vite   #it looks like react-swc plugin might be cause of the warning I am turning off?
  dev:     VITE_CJS_IGNORE_WARNING=true vite
  build:   tsc && vite build
  preview: vite preview --port 5173
  lint:    eslint . --ext js,jsx,ts,tsx

browserslist:   # vite ignores this ,uses fine grained js targets (esnext, es2021, etc) but its postCss does exploit it
  production:  &prod ["Chrome >= 112", "Edge >= 112", "Firefox >= 112", "Safari >= 16.4"]
  development: *prod # use same targets for dev and prod


