export enum City {
  Albuquerque  = 'Albuquerque',
  Atlanta      = 'Atlanta',
  Calgary      = 'Calgary',
  Chicago      = 'Chicago',
  Dallas       = 'Dallas',
  Denver       = 'Denver',
  Duluth       = 'Duluth',
  Helena       = 'Helena',
  KansasCity   = 'KansasCity',
  LosAngeles   = 'Los Angeles',
  Miami        = 'Miami',
  Montreal     = 'Montreal',
  NewOrleans   = 'NewOrleans',
  NewYork      = 'NewYork',
  SaltLakeCity = 'Salt Lake City',
  SanFrancisco = 'San Francisco',
  Seattle      = 'Seattle',
  Washington   = 'Washington',
  Winnipeg     = 'Winnipeg',
}
