export enum City {
  Albuquerque  = 'Albuquerque',
  Atlanta      = 'Atlanta',
  Calgary      = 'Calgary',
  Chicago      = 'Chicago',
  Dallas       = 'Dallas',
  Denver       = 'Denver',
  Duluth       = 'Duluth',
  Helena       = 'Helena',
  KansasCity   = 'KansasCity',
  LosAngeles   = 'Los Angeles',
  Miami        = 'Miami',
  Montreal     = 'Montreal',
  NewOrleans   = 'NewOrleans',
  NewYork      = 'NewYork',
  SaltLakeCity = 'Salt Lake City',
  SanFrancisco = 'San Francisco',
  Seattle      = 'Seattle',
  Washington   = 'Washington',
  Winnipeg     = 'Winnipeg',
}

export const Cities: Record<string, City> =
{
    Albuquerque:  City.Albuquerque,
    Atlanta:      City.Atlanta,
    Calgary:      City.Calgary,
    Chicago:      City.Chicago,
    Dallas:       City.Dallas,
    Denver:       City.Denver,
    Duluth:       City.Duluth,
    Helena:       City.Helena,
    KansasCity:   City.KansasCity,
    LosAngeles:   City.LosAngeles,
    Miami:        City.Miami,
    Montreal:     City.Montreal,
    NewOrleans:   City.NewOrleans,
    NewYork:      City.NewYork,
    SaltLakeCity: City.SaltLakeCity,
    SanFrancisco: City.SanFrancisco,
    Seattle:      City.Seattle,
    Washington:   City.Washington,
    Winnipeg:     City.Winnipeg,
};
